- configure_kernel:
  - write_in:
    - /etc/kernel-img.conf
    - |
      do_symlinks = yes
      relative_links = yes
      do_bootloader = yes
      do_bootfloppy = no
      do_initrd = yes
      link_in_boot = no

- update_initramfs:
  - exec_in: update-initramfs -u

- reconfigure_extlinux:
  - exec_in: apt-get -y --force-yes --install-suggests --reinstall install extlinux
  - exec_in: extlinux --install /boot/extlinux 2>&1
  - exec_in: extlinux-update 2>&1
